-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 20:36:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diRead
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diRead
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diRead` DEFAULT CHARACTER SET utf8 ;
USE `diRead` ;

-- -----------------------------------------------------
-- Table `diRead`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diRead`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diRead`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diRead`.`categories` (
  `id_categories` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_categories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diRead`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diRead`.`books` (
  `id_books` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `cover` VARCHAR(255) NULL,
  `file_path` VARCHAR(255) NULL,
  `categories_id` INT NULL,
  PRIMARY KEY (`id_books`),
  INDEX `categories_id_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `categories_id`
    FOREIGN KEY (`categories_id`)
    REFERENCES `diRead`.`categories` (`id_categories`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diRead`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diRead`.`ratings` (
  `id_ratings` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL,
  `books_id` INT NULL,
  `review` TEXT NULL,
  PRIMARY KEY (`id_ratings`),
  INDEX `users_id_idx` (`users_id` ASC) VISIBLE,
  INDEX `books_id_idx` (`books_id` ASC) VISIBLE,
  CONSTRAINT `users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `diRead`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `books_id`
    FOREIGN KEY (`books_id`)
    REFERENCES `diRead`.`books` (`id_books`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
